language: generic
env:
  global:
    - IDE_VERSION=1.8.1
  matrix:
    - BOARD="arduino:avr:pro:cpu=8MHzatmega328"
before_install:
  - wget http://downloads.arduino.cc/arduino-$IDE_VERSION-linux64.tar.xz
  - tar xf arduino-$IDE_VERSION-linux64.tar.xz
  - mv arduino-$IDE_VERSION $HOME/arduino-ide
  - export PATH=$PATH:$HOME/arduino-ide
#  - if [[ "$BOARD" =~ "arduino:samd:" ]]; then
#      arduino --install-boards arduino:samd;
#    fi
  - buildExampleSketch() { arduino --verify --board $BOARD $PWD/examples/$1/$1.ino; }
install:
  - mkdir -p $HOME/Arduino/libraries
  - ln -s $PWD $HOME/Arduino/libraries/.
  - arduino --install-library "EnableInterrupt"
  - arduino --install-library "Low-Power"
  - arduino --pref "update.check=false" --save-prefs
script:
  - "echo $PWD"
  - "echo $HOME"
  - "ls $PWD"
  - buildExampleSketch HM-RC-4
notifications:
  email:
    on_success: change
    on_failure: change
