language: c++
env:
  global:
    - IDE_VERSION=1.8.1
    - BOARDSTM="stm32duino:STM32F1:mapleMini"
  matrix:
    - BOARD="arduino:avr:pro:cpu=8MHzatmega328"
before_install:
  - wget http://downloads.arduino.cc/arduino-$IDE_VERSION-linux64.tar.xz
  - tar xf arduino-$IDE_VERSION-linux64.tar.xz
  - mv arduino-$IDE_VERSION $HOME/arduino-ide
  - export PATH=$PATH:$HOME/arduino-ide
#  - if [[ "$BOARD" =~ "arduino:samd:" ]]; then
#      arduino --install-boards arduino:samd;
#    fi
  - buildExampleSketch() { arduino --verify --board $BOARD $PWD/examples/$1/$1.ino 2>&1 | tee /tmp/$1.log; cat /tmp/$1.log; }
  - buildCustomSketch() { arduino --verify --board $BOARD $PWD/examples/custom/$1/$1.ino; }
  - buildStm32Sketch() { arduino -v --verify --board $BOARDSTM $PWD/examples/stm32/$1/$1.ino; }
install:
  - mkdir -p $HOME/Arduino/libraries
  - ln -s $PWD $HOME/Arduino/libraries/.
  - arduino --install-library "OneWire"
  - git clone https://github.com/GreyGnome/EnableInterrupt $HOME/arduino-ide/libraries/EnableInterrupt
  - git clone https://github.com/rocketscream/Low-Power.git $HOME/arduino-ide/libraries/Low-Power
  - git clone https://github.com/adafruit/TSL2561-Arduino-Library $HOME/arduino-ide/libraries/TSL2561-Arduino-Library
  - git clone https://github.com/spease/Sensirion.git $HOME/arduino-ide/libraries/Sensirion
  - git clone https://github.com/finitespace/BME280.git  $HOME/arduino-ide/libraries//BME280
  - arduino --pref "update.check=false" --save-prefs
  - arduino --pref "boardsmanager.additional.urls=http://dan.drown.org/stm32duino/package_STM32duino_index.json" --save-prefs
  - arduino --install-boards stm32duino:STM32F1:2017.9.5
  - echo "compiler.cpp.extra_flags=-DUSE_AES -DHM_DEF_KEY=0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,0x09,0x0a,0x0b,0x0c,0x0d,0x0e,0x0f,0x10 -DHM_DEF_KEY_INDEX=0" >$HOME/arduino-ide/hardware/arduino/avr/platform.local.txt
script:
#  - "echo $PWD"
#  - "echo $HOME"
#  - "ls $PWD"
#  - buildStm32Sketch HM-DW-WM
#  - buildStm32Sketch HM-LC-SWX-SM
  - buildExampleSketch FreqTest
#  - buildExampleSketch HM-ES-TX-WM
#  - buildExampleSketch HM-LC-Bl1-FM
#  - buildExampleSketch HM-LC-Dim1PWM-CV
#  - buildExampleSketch HM-LC-SW1-BA-PCB
#  - buildExampleSketch HM-LC-SWX-SM
#  - buildExampleSketch HM-RC-4
#  - buildExampleSketch HM-RC-8
#  - buildExampleSketch HM-RC-P1
#  - buildExampleSketch HM-SEC-MDIR
#  - buildExampleSketch HM-SEC-RHS
#  - buildExampleSketch HM-SEC-SD
#  - buildExampleSketch HM-SEC-WDS
#  - buildExampleSketch HM-SEN-MDIR-WM55
#  - buildExampleSketch HM-WDS10-TH-O
#  - buildExampleSketch HM-WDS100-C6-O-2
#  - buildExampleSketch HM-LC-DW-WM
#  - buildExampleSketch HM-DW-WM
#  - buildCustomSketch HB-GEN-SENS
#  - buildCustomSketch HB-IBUT-8
#  - buildCustomSketch HB-RC-3-ENC
#  - buildCustomSketch HB-SW2-SENS
notifications:
  email:
    on_success: change
    on_failure: change
