language: generic
env:
  global:
    - IDE_VERSION=1.8.1
  matrix:
    - BOARD="arduino:avr:pro:cpu=8MHzatmega328"
before_install:
  - wget http://downloads.arduino.cc/arduino-$IDE_VERSION-linux64.tar.xz
  - tar xf arduino-$IDE_VERSION-linux64.tar.xz
  - mv arduino-$IDE_VERSION $HOME/arduino-ide
  - export PATH=$PATH:$HOME/arduino-ide
#  - if [[ "$BOARD" =~ "arduino:samd:" ]]; then
#      arduino --install-boards arduino:samd;
#    fi
  - buildExampleSketch() { arduino --verify --board $BOARD $PWD/examples/$1/$1.ino; }
  - buildCustomSketch() { arduino --verify --board $BOARD $PWD/examples/custom/$1/$1.ino; }
install:
  - mkdir -p $HOME/Arduino/libraries
  - ln -s $PWD $HOME/Arduino/libraries/.
  - arduino --install-library "OneWire"
  - git clone https://github.com/GreyGnome/EnableInterrupt $HOME/arduino-ide/libraries/EnableInterrupt
  - git clone https://github.com/rocketscream/Low-Power.git $HOME/arduino-ide/libraries/Low-Power
  - git clone https://github.com/adafruit/TSL2561-Arduino-Library $HOME/arduino-ide/libraries/TSL2561-Arduino-Library
  - git clone https://github.com/spease/Sensirion.git $HOME/arduino-ide/libraries/Sensirion
  - git clone https://github.com/finitespace/BME280.git  $HOME/arduino-ide/libraries//BME280
  - arduino --pref "update.check=false" --save-prefs
  - arduino --pref "compiler.c.extra_flags=-DUSE_AES" --save-prefs
script:
#  - "echo $PWD"
#  - "echo $HOME"
#  - "ls $PWD"
  - buildExampleSketch FreqTest
  - buildExampleSketch HM-ES-TX-WM
  - buildExampleSketch HM-LC-Bl1-FM
  - buildExampleSketch HM-LC-Dim1PWM-CV
  - buildExampleSketch HM-LC-SW1-BA-PCB
  - buildExampleSketch HM-LC-SWX-SM
  - buildExampleSketch HM-RC-4
  - buildExampleSketch HM-RC-8
  - buildExampleSketch HM-RC-P1
  - buildExampleSketch HM-SEC-MDIR
  - buildExampleSketch HM-SEC-RHS
  - buildExampleSketch HM-SEC-SD
  - buildExampleSketch HM-SEC-WDS
  - buildExampleSketch HM-SEN-MDIR-WM55
  - buildExampleSketch HM-WDS10-TH-O
  - buildExampleSketch HM-WDS100-C6-O-2
  - buildCustomSketch HB-GEN-SENS
  - buildCustomSketch HB-IBUT-8
  - buildCustomSketch HB-RC-3-ENC
  - buildCustomSketch HB-SW2-SENS
notifications:
  email:
    on_success: change
    on_failure: change
